# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T12:02:21+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field, RootModel


class ConfigExternalPriceSourceRequest(BaseModel):
    active: Optional[bool] = Field(
        False,
        description='Defines if the external price source is active (`true`) or not (`false`). If not set, the default value will be `false`.',
    )
    appName: str = Field(
        ...,
        description='Name of the app that communicates with the external pricing source',
    )


class Item1(BaseModel):
    costPrice: float = Field(
        ...,
        description='The cost price returned by the pricing API that was used by Pricing Hub. It is measured in cents, so 5000 means 50,00 in local currency.',
    )
    index: int = Field(
        ...,
        description="The same index referring to Checkout's cart that was passed to the API",
    )
    listPrice: float = Field(
        ...,
        description='The list price returned by the pricing API that was used by Pricing Hub. It is measured in cents, so 5000 means 50,00 in local currency',
    )
    price: float = Field(
        ...,
        description='The price returned by the pricing API that was used by Pricing Hub. It is measured in cents, so 5000 means 50,00 in local currency',
    )
    priceTable: str = Field(
        ..., description='The price table that was used to price the item'
    )
    priceValidUntil: str = Field(
        ...,
        description='The moment up until the price is valid. After that moment, it will be necessary to call the pricing API again. The format of the string is in RFC3339',
    )
    skuId: str = Field(..., description='The same skuId that was passed to the API')


class Item(BaseModel):
    brandId: str = Field(
        ..., description='This is the brand ID for the item', title='brandId'
    )
    categoriesIds: List[str] = Field(
        ...,
        description='ID of the categories that will be used to compute the price',
        title='categoriesIds',
    )
    index: int = Field(
        ...,
        description="This is the index of the item at Checkout's cart. It has to be unique in the items array",
        title='index',
    )
    priceTableIds: List[str] = Field(
        ...,
        description='IDs of the price tables that will be used to compute the price. More than one price table might be passed to the array. The final price rule might be more complex than the lowest or the highest price',
        title='priceTableIds',
    )
    quantity: int = Field(
        ...,
        description='This is the amount of items that will be priced. It is possible to have a volume discount for many repeated items. Hence, the price may not be the quantity of the item multiplied by the unitary price',
        title='quantity',
    )
    sellerId: str = Field(
        ..., description='This is the seller ID for the item', title='sellerId'
    )
    skuId: str = Field(
        ...,
        description='This is the sku id of the item that will be priced',
        title='skuId',
    )


class Items(RootModel[List[Item]]):
    root: List[Item] = Field(
        ...,
        description='The list of items that are to be priced by Pricing Hub',
        title='items',
    )


class Response2(BaseModel):
    items: List[Item1] = Field(
        ...,
        description='List of items and their respective prices applied by Pricing Hub',
    )


class GetPricesRequestObject(BaseModel):
    UtmCampaign: Optional[str] = Field(
        'summer',
        description='Campaign name, represented by the `utm_campaign` value in the URL that led to the order. If there is no value, use `null`',
    )
    UtmInternalCampaign: Optional[str] = Field(
        'sale',
        description='Internal campaign name, represented by the `utmi_cp` value in the URL that led to the order. If there is no value, use `null`',
    )
    UtmMedium: Optional[str] = Field(
        'social',
        description='Medium that indicates what type of traffic the customer originated from, represented by the `utm_medium` value in the URL that led to the order. If there is no value, use `null`',
    )
    UtmSource: Optional[str] = Field(
        'facebook',
        description='Traffic source, indicates where the traffic originated from according to the `utm_source` value in the URL that led to the order. If there is no value, use `null`',
    )
    email: str = Field(
        ...,
        description="The customer's email address. If there is no value, use an empty string",
    )
    items: Items
    salesChannel: str = Field(..., description="Represents Checkout's sales channel")
